Amharic: 'https://www.flickr.com/photos/adavey/3419123937/in/album-72157603275911426/'
Arabic: 'https://commons.wikimedia.org/wiki/File:Roof_hafez_tomb.jpg'
Aramaic (syriac): 'https://en.wikipedia.org/wiki/File:Sculpted_reliefs_depicting_Ashurbanipal,_the_last_great_Assyrian_king,_hunting_lions,_gypsum_hall_relief_from_the_North_Palace_of_Nineveh_(Irak),_c._645-635_BC,_British_Museum_(16722368932).jpg'
Armenian: 'https://commons.wikimedia.org/wiki/File:Malnazar_-_Decorated_Incipit_Page_-_Google_Art_Project_(6845291).jpg'
Bahasa indonesian: 'https://commons.wikimedia.org/wiki/File:Prambanan_Temple_Compounds-111988.jpg'
Batak indonesian: 'https://en.wikipedia.org/wiki/File:COLLECTIE_TROPENMUSEUM_Een_Karo_Batak_rijstschuur_TMnr_60038149.jpg'
Bengali: 'https://en.wikipedia.org/wiki/File:Dakhil_Darwaza.JPG'
Bulgarian: 'https://commons.wikimedia.org/wiki/File:MadridSkylitzesFol35r.jpg'
Danish: 'https://en.wikipedia.org/wiki/File:Anne_Hvides_Gaard_Svendborg.jpg'
Estonian: 'https://pxhere.com/en/photo/867240'
Fijian: 'https://commons.wikimedia.org/wiki/File:BureNavala2.jpg'
Filipino: 'https://en.wikipedia.org/wiki/File:Banaue-terrace.JPG'
German: 'https://pxhere.com/en/photo/1004746'
Greek: 'https://commons.wikimedia.org/wiki/File:The_Parthenon_in_Athens.jpg'
Gujarati: 'https://commons.wikimedia.org/wiki/File:Akshardham_Gandhinagar_Gujarat.jpg'
Hindi: 'https://commons.wikimedia.org/wiki/File:Decorated_Indian_elephant.jpg'
Hmong: 'https://www.flickr.com/photos/sidewalk_tribal_galleries/10879559963/'
Hungarian: 'https://commons.wikimedia.org/wiki/File:HUN-2015-Budapest-Hungarian_Parliament_(Budapest)_2015-02.jpg'
Igbo: 'https://www.flickr.com/photos/86012097@N08/15244682704/'
Indigenous north american languages: 'https://commons.wikimedia.org/wiki/File:Native_American_Loom-Woven_Beaded_Strap.jpg'
Indonesian: 'https://www.maxpixel.net/Indonesia-Architecture-Ubud-Bali-History-Temple-277349'
Japanese: 'https://commons.wikimedia.org/wiki/File:Kano_Hideyori_-_Maple_Viewers_-_Google_Art_Project.jpg'
Kachin: 'https://en.wikipedia.org/wiki/File:Bhamo-alrededores-d09.jpg'
Khmer: 'https://commons.wikimedia.org/wiki/File:Angkor_Wat_ausSO.jpg'
Kikuyu: 'https://commons.wikimedia.org/wiki/File:Kikuyu_village_02.jpg'
Korean: 'https://commons.wikimedia.org/wiki/File:Korea-Danyang-Guinsa_Daejosajeon_3038-07.JPG'
Lao: 'https://www.flickr.com/photos/blieusong/27486495634'
Latvian: 'https://en.wikipedia.org/wiki/File:Latvijas_Universit%C4%81te_-_ogre11_-_Panoramio.jpg'
Lingala: 'https://pixnio.com/people/zaire-now-democratic-republic-of-the-congo-community'
Lithuanian: 'https://commons.wikimedia.org/wiki/File:St._Peter_and_St._Paul%27s_Church_1,_Vilnius,_Lithuania_-_Diliff.jpg'
Luhya: 'https://commons.wikimedia.org/wiki/File:Elephants_at_Amboseli_national_park_against_Mount_Kilimanjaro.jpg'
Malayalam: 'https://en.wikipedia.org/wiki/File:Vadakkumnathan_Temple.jpg'
Marshallese: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Sailing_Canoe_brailed_on_starboard_tack%2C_Jaliut_Lagoon%2C_Marshall_Islands_%281899-1900%29.jpg'
Mongolian: 'https://commons.wikimedia.org/wiki/File:Gurvger.jpg'
Nepali: 'https://en.wikipedia.org/wiki/File:Durbar_Square,_Kathmandu.jpg'
Norwegian: 'https://commons.wikimedia.org/wiki/File:Norway_Hedal_Stavkirke.jpg'
Oromo: 'https://commons.wikimedia.org/wiki/File:Brooklyn_Museum_2000.123.1_Processional_Cross_(2).jpg'
Polish: 'https://en.wikipedia.org/wiki/File:Opactwo_Benedyktyn%C3%B3w_w_Ty%C5%84cu_w_zimowej_szacie.jpg'
Portugese: 'https://en.wikipedia.org/wiki/File:Sintra_znimok_7.jpg'
Punjabi: 'https://www.flickr.com/photos/o_0/15692572742/'
Romani: 'https://commons.wikimedia.org/wiki/File:Gypsy_caravan.jpg'
Romanian: 'https://en.wikipedia.org/wiki/File:Kirchenburg_Birth%C3%A4lm.jpg'
Russian: 'https://pxhere.com/en/photo/1005099'
Samoan: 'https://pixabay.com/en/plumeria-flowers-exotic-tropical-790600/'
Serbian: 'https://commons.wikimedia.org/wiki/File:Miroslav%27s_Gospel_001.jpg'
Spanish: 'https://libreshot.com/a-dancers-in-a-colorful-dress/'
Swedish: 'https://en.wikipedia.org/wiki/File:Uppsala_Domkyrka.jpg'
Taiwanese: 'https://www.flickr.com/photos/jirka_matousek/12431704084'
Tamil: 'https://en.wikipedia.org/wiki/File:Five_Rathas_Mamallapuram.JPG'
Telugu: 'https://www.flickr.com/photos/nagarjun/38792337674/'
Tongan: 'https://en.wikipedia.org/wiki/File:TO-Haamonga_A_Maui.JPG'
Ukranian: 'https://pxhere.com/en/photo/640410'
Urdu: 'https://pixabay.com/en/urdu-carvings-india-facade-antique-166959/'
Vietnamese: 'https://pxhere.com/en/photo/1421271'
